spring:
  application:
    name: controle-compras-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/controle-compras
  datasource:
    # protocolo://host:port/recurso
    url: jdbc:postgresql://localhost:5432/controle_compras_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate.jdbc.time_zone: America/Sao_Paulo
    hibernate:
      ddl-auto: none

