services:
  database:
    image: postgres
    container_name: controle-compras-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: controle_compras_db
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - controle-compras-network
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    container_name: keycloak
    ports:
      - "8081:8080"   # host:container  → http://localhost:8081
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin    # usuário inicial do admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin    # senha inicial do admin
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_LOG_LEVEL: info
      KC_HOSTNAME: localhost
    command:
      - start-dev
    networks:
      - controle-compras-network
networks:
  controle-compras-network:
    name: controle-compras-network
    driver: bridge

